### ISSUE TITLE
Move Plank dock to bottom

### ISSUE THREAD

**Issue by spottech** [budgie-remix/budgie-plank#1]
Move plank at bottom of screen

**Comment by RohanVilloth** [comment]
Nah, that'll make it an OS X clone! :stuck_out_tongue_winking_eye:

**Comment by spottech** [comment]
lol ;)

**Comment by fossfreedom** [comment]
ok - settled on the side position.  Closed

**Comment by O1iveira** [comment]
I want try this new flavor, and for me is better change the dock to button.

Is not possible?

Thanks

**Comment by fossfreedom** [comment]
Hi.  The dock can be moved using the menu option *'Plank Preferences'*. If you do not want a dock you can add the icon task list applet to the panel. Each icon button then can launch your application.
