### ISSUE TITLE
make repo obsolete when upstream implements inbuilt theming

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-plank#3]
Apparently according to this issue https://github.com/horst3180/arc-theme/issues/570 if a GTK theme implements the theme within the GTK theme itself then we dont need to worry about bunding a separate package.

Monitor bug report - if implemented then budgie-plank package can be deleted.

**Comment by jlu5** [comment]
For what it's worth, it's possible to create an `arc-plank-theme` Debian package or similar from the same source tree as the regular GTK theme. Adding a `debian/arc-plank-theme.install` file with the text `extra/Arc-Plank usr/share/plank/themes` would simply copy the files in question to the destination, with no Makefile needed. https://www.debian.org/doc/manuals/maint-guide/dother.en.html#install

**Comment by fossfreedom** [comment]
That is actually an excellent idea. Need to find the time to make the change, test it and then push to Debian.

**Comment by fossfreedom** [comment]
ok - resolved - pushed to Debian.

changing the plank theme to GTK+ will now pick up the arc-theme without needing the extra package.

This fix will be available for budgie-remix users from 16.10 onwards.
